### ISSUE TITLE
Modals are non-functional in J3.5.1/JG 3.2.2

### ISSUE THREAD

**Issue by Hackwar** [JoomGallery/JoomGallery#84]
In the combination of Joomla 3.5.1 and JoomGallery 3.2.2, the modals to select a user (for example in the image manager to filter for an owner or in the batch view to set a new owner) don't work. They open and display the expected list of users, but when clicking on a user, nothing happens. This seems to be the case because the fields of JoomGallery still expect to use the jSelectUser_ mootools modals, but Joomla has switched those to another format. It would be really great if you could provide a patch release for this.

**Comment by Erftralle** [comment]
Pull request #79 should fix this.

**Comment by Hackwar** [comment]
That PR indeed fixes the user selection in the batch view, but it does not fix the user selection in the filter in the image manager.

**Comment by Erftralle** [comment]
> ... , but it does not fix the user selection in the filter in the image manager.

Can't confirm. Filtering in image manager works for me. 

Did you test with current master, since there were some other pull request dealing with the filtering in image manager ( #55 ).

**Comment by Hackwar** [comment]
I've tested with 3.2.2 :wink: Ok, so these bugs seem to have been resolved. Closing this one.

**Comment by Erftralle** [comment]
> Ok, so these bugs seem to have been resolved. Closing this one.

Sounds like you didn't do a real check, sorry, if I am wrong.  I would be glad if you could give a test feedback at #79.
